"use client";
import React, { useState } from "react";
import ReCAPTCHA from "react-google-recaptcha";
import toast from "react-hot-toast";

// Utility function for className merging
const cn = (...classes) => {
  return classes.filter(Boolean).join(" ");
};

// Card Components
const Card = React.forwardRef(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      "rounded-xl border bg-card text-card-foreground shadow",
      className
    )}
    {...props}
  />
));
Card.displayName = "Card";

const CardContent = React.forwardRef(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
));
CardContent.displayName = "CardContent";

// Input Component
const Input = React.forwardRef(({ className, type, ...props }, ref) => {
  return (
    <input
      type={type}
      className={cn(
        "flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-sm transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        className
      )}
      ref={ref}
      {...props}
    />
  );
});
Input.displayName = "Input";

// Textarea Component
const Textarea = React.forwardRef(({ className, ...props }, ref) => {
  return (
    <textarea
      className={cn(
        "flex min-h-[60px] w-full rounded-md border border-input bg-transparent px-3 py-2 text-base shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        className
      )}
      ref={ref}
      {...props}
    />
  );
});
Textarea.displayName = "Textarea";

// Select Component
const Select = React.forwardRef(({ className, children, ...props }, ref) => {
  return (
    <select
      className={cn(
        "flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        className
      )}
      ref={ref}
      {...props}
    >
      {children}
    </select>
  );
});
Select.displayName = "Select";

// Button Component
const Button = React.forwardRef(({ className, ...props }, ref) => {
  return (
    <button
      className={cn(
        "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50",
        className
      )}
      ref={ref}
      {...props}
    />
  );
});
Button.displayName = "Button";

const ContactSection = () => {
  const [formData, setFormData] = useState({
    lastName: "",
    firstName: "",
    email: "",
    phone: "",
    company: "",
    inquiryType: "",
    message: "",
  });
  
  // ========== reCAPTCHA STATE ==========
  // This stores the token generated by reCAPTCHA after user verification
  const [captchaToken, setCaptchaToken] = useState(null);
  const [loading, setLoading] = useState(false);

  // Content for the form
  const content = {
    title: "Get in touch",
    heading: "Connect With Us",
    description: "Have Questions About Our Products? We're Here to Help.",
    formFields: [
      { placeholder: "Last Name", type: "text" },
      { placeholder: "First Name", type: "text" },
      { placeholder: "Email", type: "email" },
      { placeholder: "Phone Number", type: "tel" },
    ],
    companyLabel: "Company Name",
    inquiryTypeLabel: "Inquiry Type",
    inquiryTypeOptions: [
      "Select inquiry type",
      "Product Information",
      "Wholesale Inquiry",
      "Distribution Partnership",
      "Other",
    ],
    messagePlaceholder: "Message",
    captchaError: "⚠️ Please complete the reCAPTCHA verification",
    buttonText: "Send Inquiry",
  };



  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  // ========== reCAPTCHA HANDLERS ==========
  
  // Called when reCAPTCHA is successfully completed
  // Receives a token that we send to the backend for verification
  const handleCaptchaChange = (token) => {
    setCaptchaToken(token);
  };

  // Called when reCAPTCHA token expires (usually after 2 minutes)
  const handleCaptchaExpired = () => {
    setCaptchaToken(null);
  };

  // submit form
  const handleSubmit = async (e) => {
    e.preventDefault();


    // Validation functions
    const validateEmail = (email) => {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      return emailRegex.test(email);
    };

    const validatePhone = (phone) => {
      // Allows international format with +, numbers, spaces, hyphens, parentheses
      const phoneRegex = /^[\+]?[1-9][\d]{0,15}$|^[\+]?[(]?[\d\s\-()]{10,}$/;
      const digitsOnly = phone.replace(/\D/g, "");
      return (
        phoneRegex.test(phone) &&
        digitsOnly.length >= 10 &&
        digitsOnly.length <= 15
      );
    };

    const validateMessage = (message) => {
      return message.trim().length >= 5;
    };

    const validateName = (name) => {
      return name.trim().length >= 2;
    };

    // Field-specific validation messages
    const validationMessages = {
      firstNameRequired: "First name is required",
      firstNameMinLength: "First name must be at least 2 characters",
      lastNameRequired: "Last name is required",
      lastNameMinLength: "Last name must be at least 2 characters",
      emailRequired: "Email is required",
      emailInvalid: "Please enter a valid email address",
      phoneRequired: "Phone number is required",
      phoneInvalid: "Please enter a valid phone number (10-15 digits)",
      companyRequired: "Company name is required",
      inquiryTypeRequired: "Inquiry type is required",
      messageRequired: "Message is required",
      messageMinLength: "Message must be at least 5 characters long",
    };

    // Validate all fields
    const {
      firstName,
      lastName,
      email,
      phone,
      company,
      inquiryType,
      message,
    } = formData;

    // First Name validation
    if (!firstName.trim()) {
      toast.error(validationMessages.firstNameRequired);
      return;
    }
    if (!validateName(firstName)) {
      toast.error(validationMessages.firstNameMinLength);
      return;
    }

    // Last Name validation
    if (!lastName.trim()) {
      toast.error(validationMessages.lastNameRequired);
      return;
    }
    if (!validateName(lastName)) {
      toast.error(validationMessages.lastNameMinLength);
      return;
    }

    // Email validation
    if (!email.trim()) {
      toast.error(validationMessages.emailRequired);
      return;
    }
    if (!validateEmail(email)) {
      toast.error(validationMessages.emailInvalid);
      return;
    }

    // Phone validation
    if (!phone.trim()) {
      toast.error(validationMessages.phoneRequired);
      return;
    }
    if (!validatePhone(phone)) {
      toast.error(validationMessages.phoneInvalid);
      return;
    }

    // Company validation
    if (!company.trim()) {
      toast.error(validationMessages.companyRequired);
      return;
    }

    // Inquiry Type validation
    if (!inquiryType.trim()) {
      toast.error(validationMessages.inquiryTypeRequired);
      return;
    }

    // Message validation
    if (!message.trim()) {
      toast.error(validationMessages.messageRequired);
      return;
    }
    if (!validateMessage(message)) {
      toast.error(validationMessages.messageMinLength);
      return;
    }

    setLoading(true);

    try {
      const response = await fetch("/api/sendEmail", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...formData,
         
        }),
      });

      const result = await response.json();

      if (result.success) {
        toast.success("Thank you! Email sent successfully!");
        setFormData({
          lastName: "",
          firstName: "",
          email: "",
          phone: "",
          company: "",
          inquiryType: "",
          message: "",
        });
       
        // Reset reCAPTCHA widget after successful submission
     
      } else {
        toast.error("❌ " + (result.error || "Failed to send email"));
      }
    } catch (error) {
      console.error("Email send error:", error);
      toast.error("❌ Failed to send: " + error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <section
      id="contact"
      className="w-full relative min-h-screen bg-[#090c17]"
      dir="ltr"
    >
      {/* Background Image Container */}
      <div className="absolute inset-0 w-full h-full bg-[#090c17]">
        <img
          className="w-full h-full object-cover"
          alt="get in touch"
          src="/assets/get-in-touch-bg.png"
        />
        <div className="absolute inset-0 w-full h-full bg-[#ffffff99] backdrop-blur backdrop-brightness-[100%] [-webkit-backdrop-filter:blur(8px)_brightness(100%)]" />
      </div>

      {/* Header Section */}
      <header className="relative z-10 pt-8 md:pt-16 lg:pt-[67px] flex flex-col items-center gap-2 md:gap-[7px] text-center px-4">
        <h1 className="font-['Poppins',Helvetica] font-normal text-transparent text-3xl sm:text-4xl md:text-5xl lg:text-[70px] leading-tight">
          <span className="font-extrabold text-black tracking-[0]">
            {content.title}
          </span>
        </h1>
      </header>

      {/* Main Content Container */}
      <div className="relative z-10 flex-1 flex items-center justify-center px-4 sm:px-6 md:px-8 lg:px-12 xl:px-48 py-8 md:py-16">
        <Card className="w-full max-w-6xl bg-white backdrop-blur-[25px] rounded-lg md:rounded-[20px] border-2 border-[#090c170d] shadow-xl">
          <CardContent className="p-4 sm:p-6 md:p-8 lg:p-10">
            <div className="flex flex-col lg:flex-row items-start justify-between gap-8 md:gap-12 lg:gap-16 mt-8 md:mt-0">
              {/* Contact Form Section */}
              <div className="w-full lg:flex-1 lg:order-1">
                <div className="flex flex-col gap-6">
                  {/* Heading */}
                  <div className="flex flex-col gap-2 w-full text-left">
                    <h2 className="font-bold text-[#444444] text-xl md:text-2xl lg:text-[24px]">
                      {content.heading}
                    </h2>
                    <p className="opacity-80 font-['Inter',Helvetica] text-[#444444] text-sm md:text-base">
                      {content.description}
                    </p>
                  </div>

                  {/* Form Fields */}
                  <form
                    onSubmit={handleSubmit}
                    className="flex flex-col gap-4 w-full"
                  >
                    {/* Form Type Selection - Radio Buttons */}
                    {/* Name fields */}
                    <div className="flex flex-col sm:flex-row gap-4">
                      <Input
                        name="firstName"
                        value={formData.firstName}
                        onChange={handleChange}
                        placeholder={content.formFields[1].placeholder}
                        className="w-full bg-[#ffffff0d] border border-[#00000033] rounded-[5px] px-3 py-2 text-sm md:text-base"
                        required
                      />
                      <Input
                        name="lastName"
                        value={formData.lastName}
                        onChange={handleChange}
                        placeholder={content.formFields[0].placeholder}
                        className="w-full bg-[#ffffff0d] border border-[#00000033] rounded-[5px] px-3 py-2 text-sm md:text-base"
                        required
                      />
                    </div>

                    {/* Email */}
                    <Input
                      name="email"
                      type="email"
                      value={formData.email}
                      onChange={handleChange}
                      placeholder={content.formFields[2].placeholder}
                      className="w-full bg-[#ffffff0d] border border-[#00000033] rounded-[5px] px-3 py-2 text-sm md:text-base"
                      required
                    />

                    {/* Phone */}
                    <Input
                      name="phone"
                      type="tel"
                      value={formData.phone}
                      onChange={handleChange}
                      placeholder={content.formFields[3].placeholder}
                      className="w-full bg-[#ffffff0d] border border-[#00000033] rounded-[5px] px-3 py-2 text-sm md:text-base"
                      required
                    />

                    {/* Select */}
                    <div>
                      <label className="block text-sm font-medium text-[#444444] mb-2 text-left">
                        {content.companyLabel}
                      </label>
                      <Input
                        name="company"
                        value={formData.company}
                        onChange={handleChange}
                        placeholder={content.companyLabel}
                        className="w-full bg-[#ffffff0d] border border-[#00000033] rounded-[5px] px-3 py-2 text-sm md:text-base"
                        required
                      />
                    </div>

                    {/* Inquiry Type Select */}
                    <div>
                      <label className="block text-sm font-medium text-[#444444] mb-2 text-left">
                        {content.inquiryTypeLabel}
                      </label>
                      <Select
                        name="inquiryType"
                        value={formData.inquiryType}
                        onChange={handleChange}
                        className="w-full bg-[#ffffff0d] border border-[#00000033] rounded-[5px] px-3 py-2 text-sm md:text-base"
                        required
                      >
                        {content.inquiryTypeOptions.map((option, idx) => (
                          <option key={idx} value={idx === 0 ? "" : option}>
                            {option}
                          </option>
                        ))}
                      </Select>
                    </div>

                    {/* Message */}
                    <Textarea
                      name="message"
                      value={formData.message}
                      onChange={handleChange}
                      placeholder={content.messagePlaceholder}
                      className="w-full h-24 md:h-[111px] bg-[#ffffff0d] border border-[#00000033] rounded-[5px] px-3 py-3 text-sm md:text-base resize-none"
                      required
                    />

                    {/* ========== reCAPTCHA COMPONENT ========== */}
                    {/* reCAPTCHA widget that displays the "I'm not a robot" checkbox
                      - sitekey: Public key from Google reCAPTCHA (stored in environment variables)
                      - onChange: Called when user successfully completes the challenge
                      - onExpired: Called when the token expires (usually after 2 minutes)
                    */}
                  

                    {/* Submit */}
                    <Button
                      type="submit"
                      disabled={loading }
                      className="w-full py-3 bg-[#032174] hover:bg-[#032174]/90 rounded-full text-white font-medium text-sm md:text-base disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {loading ? "Sending..." : content.buttonText}
                    </Button>
                  </form>
                </div>
              </div>

              {/* Image Section */}
              <div className="w-full lg:flex-1 flex justify-center lg:order-2">
                <div className="w-full max-w-[400px] lg:max-w-full lg:mt-10">
                  <img
                    className="w-full h-auto max-h-[500px] lg:max-h-[600px] object-contain rounded-lg shadow-lg"
                    alt="get in touch"
                    src="/assets/contact.png"
                  />
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </section>
  );
};

export default ContactSection;